### ISSUE TITLE
duplicate entry 'code' in validation file for Media

### ISSUE THREAD

**Issue by muldos** [BitBagCommerce/SyliusCmsPlugin#167]
Hi, 
I've found a bug in Media.yml file :
```
properties:
        code:
            - NotBlank:
                message: 'bitbag_sylius_cms_plugin.media.code.not_blank'
                groups: ['bitbag']
            - Length:
                min: 2
                max: 250
                minMessage: 'bitbag_sylius_cms_plugin.media.code.min_length'
                maxMessage: 'bitbag_sylius_cms_plugin.media.code.max_length'
                groups: ['bitbag']
        code:
            - NotBlank:
                groups: ['bitbag']
```

there is 2 'code' entries, the second one should be removed.

Best regards,

David
