### ISSUE TITLE
Disable localised URLs

### ISSUE THREAD

**Issue by KriBetko** [BitBagCommerce/SyliusCmsPlugin#182]
How to disable localised URLs? It's posible?

**Comment by bitbager** [comment]
You need to override shop routing inside the vendor.

**Comment by KriBetko** [comment]
Just create `app/Resources/BitBagSyliusCmsPlugin/config/routing.yml` file with this code:
```
bitbag_sylius_cms_plugin_admin:
    resource: "@BitBagSyliusCmsPlugin/Resources/config/routing/admin.yml"
    prefix: /admin

bitbag_sylius_cms_plugin_shop:
    resource: "@BitBagSyliusCmsPlugin/Resources/config/routing/shop.yml"
    prefix: /

sylius_sitemap:
   resource: "@SitemapPlugin/Resources/config/routing.yml"
```
Removed `{_locale}` from `bitbag_sylius_cms_plugin_shop.prefix`
