### ISSUE TITLE
Can't render more than one block or media per cms page

### ISSUE THREAD

**Issue by philipperaemdonck** [BitBagCommerce/SyliusCmsPlugin#192]
I created a CMS page and several blocks using fixtures. Here is the content of my page:
```
page:
    options:
        custom:
            test_page:
                translations:
                    fr_FR:
                        name: "test"
                        slug: "test"
                        content: |
                            {{ bitbag_cms_render_block('block_first') }}
                            {{ bitbag_cms_render_block('block_second') }}
                            {{ bitbag_cms_render_block('block_third') }}
```

But only the first block is rendered, the other are not and on the page I can see `{{ bitbag_cms_render_block('block_second') }}` and `{{ bitbag_cms_render_block('block_third') }}` as text.
Same things goes for media, only the first one is rendered.
Inside a block I tried to render several blocks and got the same problem.

However if I add:
```
{{ bitbag_cms_render_block('block_first') }}
{{ bitbag_cms_render_block('block_second') }}
{{ bitbag_cms_render_block('block_third') }}
```
inside the homepage template I can see my blocks without any issue. But when I include them inside a CMS page I only see the first block.
