### ISSUE TITLE
Add a serializer for Media autocomplete

### ISSUE THREAD

**Issue by maximehuran** [BitBagCommerce/SyliusCmsPlugin#199]
I added it in my AppBundle, but I think it can be a useful feature for somebody else ❤️

`Entity.Media.yml`
```yml
BitBag\SyliusCmsPlugin\Entity\Media:
    exclusion_policy: ALL
    xml_root_name: media
    properties:
        id:
            expose: true
            type: integer
            xml_attribute: true
            groups: [Autocomplete]
        code:
            expose: true
            type: string
            groups: [Autocomplete]
    virtual_properties:
        getName:
            serialized_name: name
            groups: [Autocomplete]
```

Routing : 
```yml
bitbag_sylius_cms_plugin_admin_ajax_media_by_name_phrase:
    path: /ajax/medias/search
    methods: [GET]
    defaults:
        _format: json
        _controller: bitbag_sylius_cms_plugin.controller.media:indexAction
        _sylius:
            serialization_groups: [Autocomplete]
            permission: true
            repository:
                method: findByNamePart
                arguments:
                    phrase: $phrase
                    locale: null

bitbag_sylius_cms_plugin_admin_ajax_media_by_code:
    path: /ajax/medias/code
    methods: [GET]
    defaults:
        _format: json
        _controller: bitbag_sylius_cms_plugin.controller.media:indexAction
        _sylius:
            serialization_groups: [Autocomplete]
            permission: true
            repository:
                method: findBy
                arguments: [code: $code]
```

`theme.html.twig` : 
```
    {{ form_row(form, {'remote_url': path('bitbag_sylius_cms_plugin_admin_ajax_media_by_name_phrase'), 'load_edit_url': path('bitbag_sylius_cms_plugin_admin_ajax_media_by_code')}) }}
```

`MediaAutocompleteChoiceType` : 
```php
<?php

declare(strict_types=1);

namespace BitBag\SyliusCmsPlugin\Form\Type;

use Sylius\Bundle\ResourceBundle\Form\Type\ResourceAutocompleteChoiceType;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormInterface;
use Symfony\Component\Form\FormView;
use Symfony\Component\OptionsResolver\OptionsResolver;

class MediaAutocompleteChoiceType extends AbstractType
{
    /**
     * {@inheritdoc}
     */
    public function configureOptions(OptionsResolver $resolver): void
    {
        $resolver->setDefaults([
            'resource' => 'bitbag_sylius_cms_plugin.media',
            'choice_name' => 'name',
            'choice_value' => 'code',
        ]);
    }

    /**
     * {@inheritdoc}
     */
    public function buildView(FormView $view, FormInterface $form, array $options): void
    {
        $view->vars['remote_criteria_type'] = 'contains';
        $view->vars['remote_criteria_name'] = 'phrase';
    }

    /**
     * {@inheritdoc}
     */
    public function getBlockPrefix(): string
    {
        return 'bitbag_sylius_cms_plugin_media_autocomplete_choice';
    }

    /**
     * {@inheritdoc}
     */
    public function getParent(): string
    {
        return ResourceAutocompleteChoiceType::class;
    }
}
```
