### ISSUE TITLE
_sylius settings on bitbag_sylius_cms_plugin_shop_block_render are not used

### ISSUE THREAD

**Issue by stefandoorn** [BitBagCommerce/SyliusCmsPlugin#222]
This is the definition:

```yaml
bitbag_sylius_cms_plugin_shop_block_render:
    path: /block/{code}
    methods: [GET]
    defaults:
        _controller: bitbag_sylius_cms_plugin.controller.block:renderBlockAction
        _sylius:
            repository:
                method: findOneByCode
                arguments:
                    - $code
```

The bottom part is ignored:

```yaml
        _sylius:
            repository:
                method: findOneByCode
                arguments:
                    - $code
```

Inside the Controller another resolver class/method is used, which uses the `findOneEnabledByCode` method internally.
