### ISSUE TITLE
Splitting fixtures into separate files gives an error

### ISSUE THREAD

**Issue by igormukhingmailcom** [BitBagCommerce/SyliusCmsPlugin#315]
Lets say we have `cms` suite, and configs placed at 2 files:

```
# config/fixtures/cms/frontpage/frontpage_about_us.yaml
sylius_fixtures:
    suites:
        cms:
            fixtures:
                block:
                    options:
                        custom:
                            frontpage_about_us:
                                ...
```

```
config/fixtures/cms/frontpage/frontpage_product_slider.yaml
sylius_fixtures:
    suites:
        cms:
            fixtures:
                block:
                    options:
                        custom:
                            frontpage_product_slider:
                                ...
```

When we try to load this suite - we will get exception:

```
Argument 1 passed to BitBag\SyliusCmsPlugin\Fixture\Factory\BlockFixtureFactory::createBlock() must be of the type string, int given, called in /vendor/bitbag  
  /cms-plugin/src/Fixture/Factory/BlockFixtureFactory.php on line 100 
```

Debugging will show that we have first block's key as expected (`frontpage_about_us`), when second block's (`frontpage_product_slider`) key is `0` for some reason (and `1`, `2`, etc if we have more files - all keys except the first one rewritten).

Things were working before splitting into separate files.

So I guess its something related to configuration merging.

Looks like somehow related to #249

**Comment by igormukhingmailcom** [comment]
## Workaround is you want to have cms fixtures splitted into separate files

You should set unique keys for fixtures, like this:

```
sylius_fixtures:
    suites:
        cms:
            fixtures:
                cms_block_frontpage_about_us: # <---------------------
                    name: block # <---------------------
                    options:
                        custom:
                            frontpage_about_us:
                                channels:
```

```
sylius_fixtures:
    suites:
        cms:
            fixtures:
                cms_block_frontpage_product_slider: # <---------------------
                    name: block # <---------------------
                    options:
                        custom:
                            frontpage_product_slider:
```
