### ISSUE TITLE
Show media in only one product associated

### ISSUE THREAD

**Issue by barotyson** [BitBagCommerce/SyliusCmsPlugin#393]
I tried to associate one media or file to just one product but its shown in all products
i have {{ bitbag_cms_render_media('test_pdf') }} in my twig file and in sylius_ui.yaml i added this code:
```
sylius_ui:
  events:
    sylius.shop.product.show.content:
      blocks:
        product_media:
          template: 'App\\Product\\_product_media.html.twig'
          priority: 20
```
in the admin panel i created a media with a product selected but doesn't work.
where i'm wrong?
