### ISSUE TITLE
How it is possible to override the validation rules?

### ISSUE THREAD

**Issue by alexmixaylov** [BitBagCommerce/SyliusCmsPlugin#399]
I need to rewrite the validation rules for the translation page (need to make the "content" field optional)
But instead of overriding the rules, I get the concatenation of them

```
# config/validator/validation.yaml

BitBag\SyliusCmsPlugin\Entity\PageTranslation:
  properties:
    content:
      - NotBlank:
        allowNull: true
        groups: [bitbag]
```

I can manage other rules for this field for example length restrictions
but unfortunately it is not possible to make this field optional

this way it does not work

```
content:
  - Blank:
    groups: [bitbag]
```
or
```
content:
  - 'isNull':
    groups: [bitbag]
```
please tell me what I'm doing wrong

**Comment by piotrleo** [comment]
According to Sylius documentation the only way to override validation rules is to overwrite them completely. You have to create your own validation group and assign it to rules. It isn't working yet but there is a PR, created today, which resolves this problem. I have exact solution for your example:

**Comment by piotrleo** [comment]
According to Sylius documentation the only way to override validation rules is to overwrite them completely. You have to create your own validation group and assign it to rules. It isn't working yet but there is a PR, created today, which resolves this problem. 

I have solution for your example:

1. You have to create following file `config/validator/validation.yaml` and copy rules for chosen Resource, in your case the file content would be similar to that: 
```
BitBag\SyliusCmsPlugin\Entity\PageTranslation:
    constraints:
        - Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity:
              fields: [slug, locale]
              errorPath: slug
              groups: [custom]
              message: bitbag_sylius_cms_plugin.page.slug.unique
    properties:
        name:
            - NotBlank:
                  message: bitbag_sylius_cms_plugin.page.name.not_blank
                  groups: [custom]
            - Length:
                  min: 2
                  max: 250
                  minMessage: bitbag_sylius_cms_plugin.page.name.min_length
                  maxMessage: bitbag_sylius_cms_plugin.page.name.max_length
                  groups: [custom]
        slug:
            - NotBlank:
                  message: bitbag_sylius_cms_plugin.page.slug.not_blank
                  groups: [custom]
            - Length:
                  min: 2
                  max: 250
                  minMessage: bitbag_sylius_cms_plugin.page.slug.min_length
                  maxMessage: bitbag_sylius_cms_plugin.page.slug.max_length
                  groups: [custom]
        metaKeywords:
            - Length:
                  min: 2
                  max: 1000
                  minMessage: bitbag_sylius_cms_plugin.page.meta_keywords.min_length
                  maxMessage: bitbag_sylius_cms_plugin.page.meta_keywords.max_length
                  groups: [custom]
        metaDescription:
            - Length:
                  min: 2
                  max: 5000
                  minMessage: bitbag_sylius_cms_plugin.page.meta_description.min_length
                  maxMessage: bitbag_sylius_cms_plugin.page.meta_description.max_length
                  groups: [custom]
        content:
            - Length:
                  min: 2
                  minMessage: bitbag_sylius_cms_plugin.page.content.min_length
                  groups: [custom]
```
2.  You have to set new validation group for chosen Resource. In my case it's "custom".
``` 
parameters:
    locale: en_US
    bitbag_sylius_cms_plugin.form.type.translation.page.validation_groups: [custom]
    bitbag_sylius_cms_plugin.form.type.page.validation_groups: [custom]
```
3. You have to overwrite your form like in Sylius docs: https://docs.sylius.com/en/latest/customization/form.html, to prevent your field from being required.

And that's basically it. When the PR [link](https://github.com/BitBagCommerce/SyliusCmsPlugin/pull/406) will be approved I'll let you know and you'll be able to override validation rules.
