### ISSUE TITLE
Add render block controller

### ISSUE THREAD

**Issue by bitbager** [BitBagCommerce/SyliusCmsPlugin#42]
For now, we are rendering block through the Twig function. I think that making it with a custom controller would be more flexible as it can have an optional template parameter. Sometimes the default CMS Block templates are not enough. What I would like to achieve is I want it to be rendered like this: `{{ render(path('bitbag_cms_render_block', {'code' : 'homepage_slide_1', 'template' : '@App/Cms/homepageSlide.html.twig'})) }}` instead of `{{ bitbag_render_block('homepage_slide_1') }}`.  Maybe it would be also a nice idea to allow an optional parameter to the `bitbag_render_block` function for a template.

**Comment by kochen** [comment]
@bitbager thanks to the `ResourceController` this is already possible by simple adding:
```
bitbag_shop_partial_block_index_by_code:
    path: /by-code/{code}
    methods: [GET]
    defaults:
        _controller: bitbag.controller.block:indexAction
        _sylius:
            template: $template
            repository:
                method: findOneByCode
                arguments:
                    - $code
```

and then in your template you could render a block with:
```
{{ render(url('bitbag_shop_partial_block_index_by_code', {'code': 'my_image_block', 'template': '@BitBagCmsPlugin/Shop/Block/imageBlock.html.twig'})) }}
```
