### ISSUE TITLE
Extends your entities?

### ISSUE THREAD

**Issue by yanlep** [BitBagCommerce/SyliusCmsPlugin#425]
Hello, I'm using your "CMS plugin for Sylius applications" and I would like to extends your "Block" entity to add some properties (like displaying dates).

In Block.orm.yml file I see "BitBag\SyliusCmsPlugin\Entity\Block" has the type: mappedSuperclass

So I imagine I can extends it on my own project entity and add an TypeExtension but how?

I tried to define my class like this:

```
namespace App\Entity;

use App\Repository\BlockRepository;
use BitBag\SyliusCmsPlugin\Entity\Block as BaseBlock;
use Doctrine\ORM\Mapping\MappedSuperclass;
use Doctrine\ORM\Mapping\Table;

/**
 * @MappedSuperclass
 * @Table(name="bitbag_cms_block")
 */
class Block extends BaseBlock
{  
    /*
     * ORM\Column(type="boolean")
     */
    private $test;

    public function isTest(): ?bool
    {
        return $this->test;
    }

    public function setTest(bool $test): self
    {
        $this->test = $test;

        return $this;
    }
}
```

and define this in yml:
```
sylius_resource:
    resources:
        bitbag_sylius_cms_plugin.block:
            classes:
                model: App\Entity\Block
```

but it doesn't work :-/

How can achieve to add other fields on your entities?
Can you please help me on this?

Thanks by Advance.
Yannick Lepetit
