### ISSUE TITLE
When aws s3 gaufrette adapter is used for `bitbag_sylius_cms_plugin_media` filesystem path gets resolved incorrectly

### ISSUE THREAD

**Issue by gigamarr** [BitBagCommerce/SyliusCmsPlugin#431]
## Steps to reproduce
1. Override `bitbag_sylius_cms_plugin_media` adapter
```
knp_gaufrette:
    adapters:
        bitbag_sylius_cms_plugin_media:
            aws_s3:
                service_id: Aws\S3\S3Client
                bucket_name: "%env(AWS_S3_BUCKET)%"
                detect_content_type: true
                options:
                    acl: public-read
```
2. Upload media from sylius admin and check resolved path in bucket
![path](https://i.ibb.co/wcWvNgB/2022-05-21-104748-626x52-scrot.png)

Removing forward slash concatenation [here](https://github.com/BitBagCommerce/SyliusCmsPlugin/blob/9f4b386356d5e4c9486bf7f8215812bfe579a8fb/src/Uploader/MediaUploader.php#L44) resolves it but I have not checked how it plays when other type of adapter is used
