### ISSUE TITLE
Duplicated CKEditor toolbar

### ISSUE THREAD

**Issue by olimination** [BitBagCommerce/SyliusCmsPlugin#484]
**To Reproduce:**

- Install BitBag SyliusCmsPlugin according the official installation guide using CKEditor v4.22.1
- Open Sylius Admin and navigate for example to the "Blocks" section and create a new block
- You will see the CKEditor is loaded with duplicated toolbars

BitBag SyliusCmsPlugin: 4.0.6
FOSCKEditorBundle: 2.4.0
CKEditor: 4.22.1

**Screenshot:**

![image](https://github.com/BitBagCommerce/SyliusCmsPlugin/assets/662924/60b99daf-0c78-42c9-a72d-457b81fea326)

**Workaround solution**
If I add the following config in some config file like `config/packages/fos_ckeditor.yaml`:

```
fos_ck_editor:
  ...
  configs:
    bitbag_sylius_cms_plugin:
      toolbar: false
``` 
it works.

Does anybody face the same issue? Did the FOSCKEditorBundle change something regarding config handling?
It seems so that the `default_config` is loaded but also some more CKEditor config.

Thanks for your feedback.

**Comment by Gorkyman** [comment]
@olimination I can confirm that the same thing is happening to me and your solution resolves the issue.

**Comment by stefanz92** [comment]
I can also confirm but your solution is not the best because this will load the default toolbar with all options, a better solution is:

```
fos_ck_editor:
    default_config: custom_toolbar
    configs:
        custom_toolbar:
            toolbar: custom_toolbar
    toolbars:
        configs:
            custom_toolbar:
                - '@standard.clipboard'
                - '@standard.editing'
                - '@standard.links'
                - '@standard.insert'
                - '@standard.tools'
                - '@standard.document'
                - '/'
                - '@standard.basic_styles'
                - '@standard.paragraph'
                - '@standard.about'
        items:
            standard.insert: ['Image', 'MediaVideo', 'MediaImage', 'Table', 'HorizontalRule', 'SpecialChar']
```
