### ISSUE TITLE
how to remove locale on the url

### ISSUE THREAD

**Issue by benyang2015** [BitBagCommerce/SyliusCmsPlugin#49]

**Comment by h3llr4iser** [comment]
I think you can create a new route without the locale parameter:

```
app_cms_shop_page_show:
    path: /page/{slug}
    methods: [GET]
    defaults:
        _controller: bitbag.controller.page:showAction
        _sylius:
            template: BitBagCmsPlugin:Page:show.html.twig
            repository:
                method: findOneByChannelAndSlug
                arguments:
                    - "expr:service('sylius.context.channel').getChannel()"
                    - "expr:service('sylius.context.locale').getLocaleCode()"
                    - $slug
```
