### ISSUE TITLE
Rendering Pages with bitbag_render_page_link_by_code

### ISSUE THREAD

**Issue by TELLO0815** [BitBagCommerce/SyliusCmsPlugin#72]
Rendering pages with slug is for multilingual pages not a good idea. Is there any prepared way how it works with the code (bitbag_render_page_link_by_code)? 

THX for some code.

**Comment by TELLO0815** [comment]
There was just a bug in your code:
`template: BitBagCmsPlugin:Shop:Page:show.html.twig`

must be 

`template: BitBagCmsPlugin:Shop/Page:show.html.twig`


on the end also the page by code:
```
bitbag_shop_page_show:
    path: /page/{slug}
    methods: [GET]
    defaults:
        _controller: bitbag.controller.page:showAction
        _sylius:
            template: BitBagCmsPlugin:Shop/Page:show.html.twig
            repository:
                method: findEnabledBySlug
                arguments:
                    - $slug
                    - "expr:service('sylius.context.locale').getLocaleCode()"

bitbag_render_pages_by_section_code:
    path: /page/section/{code}
    methods: [GET]
    defaults:
        _controller: bitbag.controller.page:indexAction
        _sylius:
            template: $template
            repository:
                method: findEnabledBySectionCode
                arguments:
                    - $code

bitbag_render_pages_by_code:
    path: /page/{code}
    methods: [GET]
    defaults:
        _controller: bitbag.controller.page:showAction
        _sylius:
            template: $template
            repository:
                method: findEnabledByCode
                arguments:
                    - $code
                    - "expr:service('sylius.context.locale').getLocaleCode()"
```
